apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skywatch.fullname" . }}-frontend
  labels:
    {{- include "skywatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "skywatch.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "skywatch.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
              name: http
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RABBITMQ_HOST
              value: {{ include "skywatch.fullname" . }}-rabbitmq
            - name: RABBITMQ_QUEUE
              value: {{ .Values.rabbitmq.queue }}
