apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skywatch.fullname" . }}-worker
  labels:
    {{- include "skywatch.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "skywatch.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "skywatch.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: RABBITMQ_HOST
              value: {{ include "skywatch.fullname" . }}-rabbitmq
            - name: RABBITMQ_QUEUE
              value: {{ .Values.rabbitmq.queue }}
