frontend:
  replicaCount: 1
  image:
    repository: ghcr.io/pinchas-python/skywatch-frontend
    tag: bf122ab
  service:
    type: NodePort
    port: 5000
    nodePort: 30080
worker:
  replicaCount: 1
  image:
    repository: ghcr.io/pinchas-python/skywatch-worker
    tag: bf122ab
rabbitmq:
  image:
    repository: rabbitmq
    tag: 3.13-management
  auth:
    username: guest
    password: guest
